apply + deploy

diff --git a/apply b/apply
--- a/apply
+++ b/apply
@@ -1,13 +1,8 @@
-#!/bin/sh
-pushd ~/.dotfiles
+#!/usr/bin/env bash
+pushd ~/.dotfiles || echo "Failed to change directory" || exit
 git add --intent-to-add .
-#sudo nixos-rebuild switch --flake .?submodules=1# --show-trace
-#sudo nixos-rebuild switch --flake path://$(pwd)# --show-trace --builders ""
 sudo -v
-#sudo nixos-rebuild switch --flake .?submodules=1# --show-trace --builders "" --log-format internal-json -v |& nom --json
-nh os switch -a .?submodules=1 -- -j0
-#sudo nixos-rebuild switch --flake .?submodules=1# --show-trace --log-format internal-json -v |& nom --json
-#sudo nixos-rebuild switch --flake path://$(pwd)# --show-trace --builders "" --log-format internal-json -v
-#sudo nixos-rebuild switch --flake path://$(pwd)# --show-trace
+# nh os switch -a .?submodules=1 -- $@ -j0 --show-trace
+nh os switch -a .?submodules=1 -- $@ --builders "" --show-trace
 #hyprctl reload
-popd
+popd || exit
